name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar pytest
        run: pip install pytest

      - name: Verificar archivos
        run: |
          pwd
          ls -la
          ls -la src
          ls -la tests

      - name: Ejecutar pruebas
        run: python -m pytest -v